/*PUT http://localhost:9494/AppfairPlay/api/jugadores/17
Content-Type: application/json

{
  "nombre": "Sebastian Modificado",
  "apellido": "Caceres Perea",
  "idPosicion": 1
}*/

PUT http://localhost:9494/AppfairPlay/api/jugadores/17
Content-Type: application/json

{
  "nombre": "juan nuevo ",
  "apellido": "Caceres Perea",
  "idPosicion": 3
}

