# esta es nuestra conexion  la base de datos creada para las pruebas
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=FairPlay;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
